apiVersion: v1
kind: ConfigMap
metadata:
  name: app-properties
data:
  appUrl: "http://my-app-service"
  timeout: "30"
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  restartPolicy: Never
  containers:
  - name: ubuntu
    image: ubuntu
    env:
    - name: "request.timeout"
      valueFrom:
        configMapKeyRef:
          name: app-properties
          key: timeout
    - name: "application.url"
      valueFrom:
        configMapKeyRef:
          name: app-properties
          key: appUrl
    args:
    - env          